### PR TITLE
add follow_joint_trajectory/feedback message publish

### PR DESCRIPTION
**Pull request by furushchev**
this enables to publish follow_joint_trajectory/feedback topic when controller is moving.
This bug is reported as #357 .

### CODE REVIEW

**Comment by ahendrix** [comment]
Have you confirmed that this works on a real PR2 or in simulation?

**Comment by furushchev** [comment]
I confirmed on a real PR2 which we use on groovy, and I think it works fine.

**Comment by ahendrix** [comment]
You've branched this from the version released into Groovy, but you're asking to merge it into Hydro. Which version(s) should this be merged into?

**Comment by furushchev** [comment]
Both if it possible, or at minimum I'd like use on groovy.

**Comment by ahendrix** [comment]
Merged manually into hydro-devel and a new groovy-devel branch. Fixes #357

**Pull request closed without merging**
