### PR TITLE
Joint Position and Velocity controllers startup fix

### PR DESCRIPTION
**Pull request by goretkin**
Fixes https://github.com/PR2/pr2_controllers/issues/374

### CODE REVIEW

**Comment by goretkin** [comment]
Sorry, I meant to merge into `groovy-devel`. I don't know how to change it. Perhaps I need to close this PR and open a new one.

I also wanted to show that this fix is what is already done in other controllers, for example: https://github.com/PR2/pr2_controllers/blob/hydro-devel/robot_mechanism_controllers/src/joint_trajectory_action_controller.cpp#L313 They also use the `starting` function to set the `last_time_`.

**Comment by goretkin** [comment]
@k-okada Hi, what does the `question` tag mean? Are you interested in maintaining this package?

**Comment by k-okada** [comment]
I'm released these package as a part of our Orphaned Maintanair Project. so not so much interested in 'maintaining' this package, sorry for that. 

I'm not sure if we should include this PR, so waiting for other users feedback. Also could you please rebase this on kinetic-devel branch?

c.f. https://github.com/PR2/rqt_pr2_dashboard/pull/20#issuecomment-365657928

**Review by v4hn — APPROVED** [review]
I did not test this on the robot,
but the changes make sense and look good to me.

Merging the commits in groovy or hydro doesn't make sense anymore in my opinion. (unless someone asks for it)
I would propose to re-open this request against kinetic (possibly indigo) and commit it there.

**Comment by v4hn** [comment]
Replaced by #404 (error code: merge event not found -.-")

**Pull request closed without merging**
